# Базовые настройки приложения
spring:
  application:
    name: car-sharing
    # Настройки базы для dev-режима (H2) и Liquibase
  datasource:
    url: jdbc:h2:file:/Users/apple/Documents/JavaProjects/CarSharing/.data/devdb;MODE=PostgreSQL;
#    DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml